"""Stitch the analysis modules into one self-contained jupytext script + notebook.

Keeping the notebook generated (rather than hand-copied) guarantees that the
published script is exactly the code that produced the figures.
"""
import re, subprocess, sys
import pandas as pd

OUT_PY = "ring_attractor_hd_sleep.py"


def strip_header(path, drop_imports=(), drop_docstring=True):
    src = open(path).read()
    if drop_docstring:
        src = re.sub(r'^""".*?"""\n', "", src, flags=re.S)
    lines = []
    for ln in src.splitlines():
        if ln.startswith(("import ", "from ")) and any(d in ln for d in drop_imports):
            continue
        lines.append(ln)
    return "\n".join(lines).strip("\n")


def md(text):
    return "# %% [markdown]\n" + "\n".join("# " + l if l else "#" for l in text.strip().splitlines())


def code(text):
    return "# %%\n" + text


def main():
    df = pd.read_csv("session_summary.csv")
    p = df.set_index("sid")
    prim = "Mouse28-140312"
    n_ses, n_mice = len(df), df.subject.nunique()

    def f(col, sid=prim, nd=2):
        return f"{p.loc[sid, col]:.{nd}f}"

    cells = []
    cells.append(md(f"""
# A continuous ring attractor in the head-direction system, maintained internally during sleep

**Dataset:** [DANDI:000056](https://dandiarchive.org/dandiset/000056) — *Internally organized
mechanisms of the head direction sense* (Peyrache, Lacroix, Petersen & Buzsáki,
*Nature Neuroscience* 2015). Extracellular recordings from anterior thalamus and
post-subiculum in freely moving mice, with an open-field foraging session flanked by
sleep, and REM / non-REM / awake state labels.

## The claim being tested

The head-direction (HD) system is usually described as a *continuous attractor*: a
population of cells whose joint activity is confined to a one-dimensional closed curve
(a ring), with one localised bump of activity whose position on that ring is the
animal's heading. Two things make this more than a redescription of the tuning curves:

1. The ring should be **intrinsic to the network**, not imposed by the sensory input.
   If the ring is generated by recurrent connectivity, it should still be there when
   the animal is asleep and the vestibular and visual heading signals are absent or
   uninformative.
2. The state on the ring should move **continuously**. A collection of independently
   modulated direction-selective neurons could produce decoded headings that jump
   arbitrarily from one moment to the next; a state on an attractor cannot leave the
   ring, so it has to travel around it.

This notebook tests both, using only spikes. Every sleep analysis below is computed
without reference to any behavioural measurement, so it cannot be inherited from the
animal's actual head movements.

## What is done

* Identify HD cells from wake tuning curves, with a circular-shift null and a
  split-half stability criterion.
* Show that the pairwise correlation structure of the HD ensemble is a cosine function
  of the difference in preferred direction, in wake **and** in REM and non-REM sleep.
* Embed the binned population activity with Isomap and show that the point cloud is a
  hollow ring in all three states, and a blob for time-shuffled data and for non-HD units.
* Decode an internal heading from the wake tuning curves during sleep, and show that
  two disjoint halves of the ensemble agree with each other (an internal coherence
  measure that never uses behaviour).
* Show that the angular coordinate of the Isomap ring is the same coordinate as the
  decoded heading, and that the internal heading moves smoothly rather than jumping.
* Repeat the whole thing on {n_ses} sessions from {n_mice} mice.
"""))

    cells.append(md("""
## Setup

Data are streamed from the DANDI S3 bucket with `remfile` and a local disk cache; no
file is downloaded in full. Analysis is done with Pynapple.
"""))
    cells.append(code(
        "import warnings, os\n"
        "warnings.filterwarnings('ignore')\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import h5py, remfile\n"
        "from pynwb import NWBHDF5IO\n"
        "import pynapple as nap\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "from matplotlib.gridspec import GridSpec\n"
        "from scipy.ndimage import gaussian_filter1d\n"
        "from sklearn.decomposition import PCA\n"
        "from sklearn.manifold import Isomap\n"
        "\n"
        "TWO_PI = 2 * np.pi"))

    cells.append(md("""
## Loading

Head direction is not stored directly in these files. It is recovered from the two
head-mounted LEDs: the vector from the red to the blue LED gives the heading, and
samples where either LED failed to track (coded as -1) are dropped. Brain-state
intervals (`Awake` / `REM` / `Non-REM`) come from the `behavior/states` table. The
wake epoch used for tuning curves is further restricted to periods with continuous
tracking, which selects the open-field foraging part of the session.

The units table in this conversion carries only spike times, with no anatomical label,
so ADn and PoSub cells are pooled and HD cells are identified functionally.
"""))
    cells.append(code(strip_header("loader.py")))

    cells.append(md("""
## Identifying head-direction cells

A unit is called an HD cell when its wake firing rate is in a plausible single-unit
range (0.5-50 Hz), its mean vector length exceeds 0.25 *and* the 99th percentile of a
circular-shift null, and its tuning curve is stable across the two halves of the wake
epoch (split-half correlation > 0.5). The null shifts the whole head-direction
sequence relative to the spikes, so it preserves both the occupancy map and each
unit's spike count, and destroys only the alignment between them.
"""))
    cells.append(code(strip_header("hdcells.py", drop_imports=("numpy", "pandas", "pynapple"))))

    cells.append(md("""
## Ring-attractor measurements

Four independent measurements are computed per brain state, all on 100 ms bins of the
HD-cell ensemble smoothed with a 200 ms Gaussian:

* **Cosine correlation structure.** For every pair of HD cells, the correlation of
  their binned firing against the difference of their wake preferred directions. On a
  ring attractor this is a cosine: cells with nearby preferred directions are
  co-active, cells with opposite preferred directions are anti-correlated.
* **Manifold shape.** Isomap embedding of the population vectors, summarised by
  *hollowness* = mean radius / SD of radius, and by how sharply the angular position on
  the ring determines the decoded heading.
* **A single angular coordinate.** The heading decoded from one random half of the
  ensemble is used to predict the activity of the other, disjoint half. Because the
  predictor and the predicted neurons never overlap, the R² cannot come from fitting
  the angle to the spikes it is scored on.
* **Internal coherence.** Two disjoint halves each decode a heading independently
  (Poisson MAP against the wake tuning curves); the mean resultant length of the
  difference between the two decoded angles measures whether the population holds a
  single consistent angular state. This never uses behaviour.

Note on dimensionality: the raw participation ratio of 100 ms binned activity stays
high (around 12 for a 25-cell ensemble) because single-trial spike counts are
noise-dominated, so it is *not* used as evidence for a low-dimensional code. What the
PCA spectrum does show is that the two leading components of the HD ensemble carry
nearly equal variance, as they must if the signal lies in a plane and traverses a ring
in it, whereas for the non-HD control PC1 dominates PC2.

The null throughout is an independent random circular time shift per neuron. It keeps
every single-neuron statistic (rate, autocorrelation, burstiness) and destroys only
the coordination between neurons.
"""))
    cells.append(code(strip_header("ringanalysis.py",
                                   drop_imports=("numpy", "pandas", "pynapple",
                                                 "scipy.ndimage", "sklearn"))))

    cells.append(md("""
## Per-session pipeline
"""))
    cells.append(code(strip_header("run_session.py", drop_imports=(
        "warnings", "numpy", "pynapple", "loader", "hdcells", "ringanalysis"))
        .replace("import ringanalysis as ra\n", "")
        .replace("ra.", "").replace("if __name__ == \"__main__\":", "if False:")))

    cells.append(md("""
## Figures
"""))
    cells.append(code(strip_header("plots.py", drop_imports=(
        "numpy", "matplotlib", "ringanalysis", "hdcells"))))

    cells.append(md(f"""
## Run

The primary session is `{prim}` ({int(p.loc[prim, 'n_hd'])} HD cells of
{int(p.loc[prim, 'n_units'])} units). Results for each session are cached to
`cache_<session>.npy`, so re-running the notebook does not repeat the analysis.
"""))
    cells.append(code(
        f"PRIMARY = '{prim}'\n"
        f"ALL_SESSIONS = {list(df.sid)!r}\n\n"
        "def get(sid):\n"
        "    fn = f'cache_{sid}.npy'\n"
        "    if os.path.exists(fn):\n"
        "        return np.load(fn, allow_pickle=True).item()\n"
        "    r = analyze(sid)\n"
        "    np.save(fn, r, allow_pickle=True)\n"
        "    return r\n\n"
        "res = {sid: get(sid) for sid in ALL_SESSIONS}\n"
        "r = res[PRIMARY]\n"
        "s = load_session(SESSIONS[PRIMARY])"))

    cells.append(md("""
### Raw data

Brain-state segmentation, the wake spike raster of the HD ensemble sorted by preferred
direction next to the measured head direction, and the same raster during REM and
non-REM sleep. The diagonal streaks in the sleep rasters are the activity bump moving
around the ring; the black dots are the heading decoded from those same spikes.
"""))
    cells.append(code("fig_overview(r, s, 'fig01_data_overview.png')"))

    cells.append(md("""
### Wake tuning curves and cell selection
"""))
    cells.append(code("fig_tuning(r, 'fig02_hd_tuning_curves.png')"))

    cells.append(md(f"""
### Correlation structure

The correlation matrix sorted by preferred direction has the same banded, wrap-around
structure in all three states. The cosine fit explains
R² = {f('cos_r2_wake')} of the pair-correlation variance in wake,
{f('cos_r2_REM')} in REM and {f('cos_r2_nREM')} in non-REM, against
{f('null_cos_r2_nREM', nd=3)} for the time-shifted null in non-REM.
"""))
    cells.append(code("fig_correlations(r, 'fig03_pairwise_correlations.png')"))

    cells.append(md(f"""
### The manifold is a ring in every state

Hollowness is {f('hollowness_wake')} in wake, {f('hollowness_REM')} in REM and
{f('hollowness_nREM')} in non-REM, versus {f('null_hollowness_nREM')} for the
time-shifted null and {f('ctrl_hollowness_nREM')} for a same-size ensemble of non-HD
units recorded simultaneously. Colour is the measured head direction in wake and the
decoded internal heading in sleep; in both cases it advances monotonically around the
ring, which is what makes this a *continuous* attractor rather than a set of discrete
states.
"""))
    cells.append(code("fig_manifold(r, 'fig04_ring_manifold.png')"))

    cells.append(md(f"""
### Dimensionality

The two leading principal components of the HD ensemble carry nearly equal variance
(PC2/PC1 = {f('pc2_pc1_nREM')} in non-REM and {f('pc2_pc1_wake')} in wake, against
{f('ctrl_pc2_pc1_nREM')} for the non-HD control), which is what a ring in a plane
looks like. The participation ratio itself stays high ({f('pr_nREM')} in non-REM)
because 100 ms spike counts are noise-dominated; that is why the ring is quantified
with the manifold and decoding measures instead. A single
angle decoded from one half of the ensemble accounts for R² = {f('ev1d_nREM')} of the
variance of the *other*, held-out half in non-REM ({f('ev1d_wake')} in wake), against
{f('null_ev1d_nREM')} for the null.
"""))
    cells.append(code("fig_dimensionality(r, 'fig05_dimensionality.png')"))

    cells.append(md(f"""
### Internal coherence and continuity of movement

Two disjoint halves of the ensemble, decoding independently, agree with resultant
length {f('split_coh_REM')} in REM and {f('split_coh_nREM')} in non-REM
({f('split_coh_wake')} in wake), against {f('null_split_coh_nREM')} for the null. The
internal heading also moves at a finite speed rather than jumping, and it moves faster
in non-REM than in REM.
"""))
    cells.append(code("fig_coherence(r, 'fig06_internal_coherence.png')"))

    cells.append(md(f"""
### The ring coordinate is the heading coordinate

During wake the decoder recovers the animal's true head direction with a median error
of {f('decode_err_median_deg', nd=0)}° (circular r = {f('decode_circ_corr')}), which
validates both the tuning curves and the decoder. The angular position on the Isomap
ring, computed with no behavioural or tuning-curve information at all, pins down the
decoded heading with residual resultant length {f('map_conc_nREM')} in non-REM and
{f('map_conc_REM')} in REM, against {f('null_map_conc_nREM')} for shuffled labels.
"""))
    cells.append(code("fig_decode_validation(r, 'fig07_decoding_validation.png')"))

    cells.append(md(f"""
### The sleeping animal's head is not driving the ring

The strongest form of the internal-maintenance claim is a direct comparison. Within
sleep episodes of at least 30 s the measured head direction is essentially fixed
(median resultant length {f('R_head_REM')} in REM and {f('R_head_nREM')} in non-REM)
while the decoded internal heading is spread around the ring ({f('R_decoded_REM')} and
{f('R_decoded_nREM')}). Over a 1 s window the head turns at
{f('head_speed_REM', nd=0)}°/s in REM and {f('head_speed_nREM', nd=0)}°/s in non-REM
while the internal heading travels {f('internal_speed_REM', nd=0)}°/s and
{f('internal_speed_nREM', nd=0)}°/s.
"""))
    cells.append(code("beh = fig_sleep_vs_behavior(r, s, 'fig09_internal_vs_measured.png',\n"
                      "                            nearest_hd=nearest_hd)"))

    cells.append(md(f"""
### Across sessions
"""))
    src = open("make_figures.py").read()
    summarize_src = src[src.index("def summarize("):src.index("if __name__ ==")].strip()
    cells.append(code(summarize_src))
    cells.append(code(
        "summary = [summarize(res[sid]) for sid in ALL_SESSIONS]\n"
        "summary[ALL_SESSIONS.index(PRIMARY)].update(beh)\n"
        "df = fig_multisession(summary, 'fig08_multisession_summary.png')\n"
        "df.to_csv('session_summary.csv', index=False)\n"
        "df[['sid', 'subject', 'n_hd', 'cos_r2_nREM', 'hollowness_nREM',\n"
        "    'ev1d_nREM', 'split_coh_nREM']]"))

    cells.append(md(f"""
## Conclusion

Across {n_ses} sessions from {n_mice} mice, the head-direction ensemble keeps the same
one-dimensional ring geometry in REM and non-REM sleep that it has during waking
exploration. The evidence is that (i) pairwise correlations remain a cosine function of
the wake preferred-direction difference, (ii) the population state cloud is a hollow
ring whose angular coordinate is the heading coordinate, (iii) two disjoint halves of
the ensemble report the same angle, and (iv) that angle moves continuously. None of
these hold for time-shifted surrogates or for simultaneously recorded non-HD units,
so the structure is a property of the coordinated population and not of single-cell
statistics.

Because the sleep measurements use no behavioural signal and the animal is not
generating informative vestibular or visual heading input, the ring has to be
maintained by the network itself. That is the defining property of a continuous
attractor. The main quantitative difference between states is the speed at which the
bump travels: it drifts several times faster in non-REM than in REM, consistent with
the time-compressed replay-like dynamics reported for this system.

### Limitations

The units table in this NWB conversion has no anatomical labels, so anterior thalamic
and post-subicular cells are pooled and the analysis cannot separate them. Isomap
hollowness is a summary statistic, not a topological proof; a persistent-homology test
would be the stronger version of the same claim. Finally, sleep states are taken as
given from the archived scoring rather than re-derived from the LFP.
"""))

    body = "\n\n".join(cells)
    header = ("# ---\n"
              "# jupyter:\n"
              "#   jupytext:\n"
              "#     text_representation:\n"
              "#       extension: .py\n"
              "#       format_name: percent\n"
              "#       format_version: '1.3'\n"
              "#   kernelspec:\n"
              "#     display_name: Python 3\n"
              "#     language: python\n"
              "#     name: python3\n"
              "# ---\n\n")
    open(OUT_PY, "w").write(header + body + "\n")
    print("wrote", OUT_PY)
    subprocess.run([sys.executable, "-m", "jupytext", "--to", "notebook", OUT_PY], check=True)


if __name__ == "__main__":
    main()
